package com.payflow.common.crypto;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Base64;

/**
 * AES-256-GCM encryption at rest for the card reference column.
 *
 * Storage format: base64(12-byte random IV || ciphertext || 16-byte GCM tag).
 * A fresh IV per value is mandatory for GCM — reusing one breaks the cipher.
 *
 * Key sourcing: AES_ENCRYPTION_KEY may be a base64-encoded 256-bit key, or any
 * string (it is then run through SHA-256 to derive 32 key bytes) so secrets
 * generated by Render's generateValue work unchanged. Spring instantiates this
 * converter as a bean (Hibernate's SpringBeanContainer), which is how the
 * property gets injected.
 */
@Component
@Converter
public class AesGcmAttributeConverter implements AttributeConverter<String, String> {

    private static final Logger log = LoggerFactory.getLogger(AesGcmAttributeConverter.class);
    private static final String TRANSFORMATION = "AES/GCM/NoPadding";
    private static final int IV_BYTES = 12;
    private static final int TAG_BITS = 128;

    private final SecretKey key;
    private final SecureRandom random = new SecureRandom();

    public AesGcmAttributeConverter(@Value("${payflow.crypto.aes-key:}") String configuredKey) {
        this.key = new SecretKeySpec(resolveKeyBytes(configuredKey), "AES");
    }

    private static byte[] resolveKeyBytes(String configured) {
        if (configured == null || configured.isBlank()) {
            log.warn("AES_ENCRYPTION_KEY is not set — using an insecure development key. "
                    + "Set it in any real environment.");
            configured = "payflow-dev-only-insecure-aes-key";
        }
        try {
            byte[] decoded = Base64.getDecoder().decode(configured);
            if (decoded.length == 32) {
                return decoded;
            }
        } catch (IllegalArgumentException ignored) {
            // Not base64 — fall through to derivation.
        }
        try {
            return MessageDigest.getInstance("SHA-256").digest(configured.getBytes(StandardCharsets.UTF_8));
        } catch (Exception e) {
            throw new IllegalStateException("Cannot derive AES key", e);
        }
    }

    @Override
    public String convertToDatabaseColumn(String attribute) {
        if (attribute == null) {
            return null;
        }
        try {
            byte[] iv = new byte[IV_BYTES];
            random.nextBytes(iv);
            Cipher cipher = Cipher.getInstance(TRANSFORMATION);
            cipher.init(Cipher.ENCRYPT_MODE, key, new GCMParameterSpec(TAG_BITS, iv));
            byte[] ciphertext = cipher.doFinal(attribute.getBytes(StandardCharsets.UTF_8));
            byte[] out = new byte[iv.length + ciphertext.length];
            System.arraycopy(iv, 0, out, 0, iv.length);
            System.arraycopy(ciphertext, 0, out, iv.length, ciphertext.length);
            return Base64.getEncoder().encodeToString(out);
        } catch (Exception e) {
            throw new IllegalStateException("Encryption failed", e);
        }
    }

    @Override
    public String convertToEntityAttribute(String dbData) {
        if (dbData == null) {
            return null;
        }
        try {
            byte[] all = Base64.getDecoder().decode(dbData);
            Cipher cipher = Cipher.getInstance(TRANSFORMATION);
            cipher.init(Cipher.DECRYPT_MODE, key,
                    new GCMParameterSpec(TAG_BITS, all, 0, IV_BYTES));
            byte[] plain = cipher.doFinal(all, IV_BYTES, all.length - IV_BYTES);
            return new String(plain, StandardCharsets.UTF_8);
        } catch (Exception e) {
            // Tampered value, wrong key, or a legacy plaintext row from before
            // encryption existed: surface nothing rather than fail the read.
            log.warn("Could not decrypt card reference — returning null");
            return null;
        }
    }
}
